[2024-05-21T18:35:42.798+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_bitcoin.train_deep_learning manual__2024-05-21T17:24:46.231076+00:00 [queued]>
[2024-05-21T18:35:42.806+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_bitcoin.train_deep_learning manual__2024-05-21T17:24:46.231076+00:00 [queued]>
[2024-05-21T18:35:42.807+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-05-21T18:35:42.815+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): train_deep_learning> on 2024-05-21 17:24:46.231076+00:00
[2024-05-21T18:35:42.836+0000] {standard_task_runner.py:57} INFO - Started process 1461 to run task
[2024-05-21T18:35:42.842+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fraud_bitcoin', 'train_deep_learning', 'manual__2024-05-21T17:24:46.231076+00:00', '--job-id', '371', '--raw', '--subdir', 'DAGS_FOLDER/fraud.py', '--cfg-path', '/tmp/tmpjjha046_']
[2024-05-21T18:35:42.849+0000] {standard_task_runner.py:85} INFO - Job 371: Subtask train_deep_learning
[2024-05-21T18:35:42.941+0000] {task_command.py:416} INFO - Running <TaskInstance: fraud_bitcoin.train_deep_learning manual__2024-05-21T17:24:46.231076+00:00 [running]> on host 66abfe055500
[2024-05-21T18:35:43.007+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fraud_bitcoin' AIRFLOW_CTX_TASK_ID='train_deep_learning' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T17:24:46.231076+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T17:24:46.231076+00:00'
[2024-05-21T18:38:28.634+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fraud.py", line 155, in train_deep_learning
    accuracy = accuracy_score(y_test, y_pred)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 220, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 93, in _check_targets
    raise ValueError(
ValueError: Classification metrics can't handle a mix of binary and multilabel-indicator targets
[2024-05-21T18:38:28.726+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fraud_bitcoin, task_id=train_deep_learning, execution_date=20240521T172446, start_date=20240521T183542, end_date=20240521T183828
[2024-05-21T18:38:28.795+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 371 for task train_deep_learning (Classification metrics can't handle a mix of binary and multilabel-indicator targets; 1461)
[2024-05-21T18:38:28.968+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-21T18:38:29.086+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
