[2024-04-28T17:31:51.382+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_transaction_analysis.explore_data manual__2024-04-28T17:25:50.549263+00:00 [queued]>
[2024-04-28T17:31:51.388+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_transaction_analysis.explore_data manual__2024-04-28T17:25:50.549263+00:00 [queued]>
[2024-04-28T17:31:51.388+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2024-04-28T17:31:51.397+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): explore_data> on 2024-04-28 17:25:50.549263+00:00
[2024-04-28T17:31:51.403+0000] {standard_task_runner.py:57} INFO - Started process 409 to run task
[2024-04-28T17:31:51.406+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_transaction_analysis', 'explore_data', 'manual__2024-04-28T17:25:50.549263+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/bitcoin-checkpoint.py', '--cfg-path', '/tmp/tmpq_movojo']
[2024-04-28T17:31:51.409+0000] {standard_task_runner.py:85} INFO - Job 152: Subtask explore_data
[2024-04-28T17:31:51.457+0000] {task_command.py:416} INFO - Running <TaskInstance: bitcoin_transaction_analysis.explore_data manual__2024-04-28T17:25:50.549263+00:00 [running]> on host 93821e8db187
[2024-04-28T17:31:51.715+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_transaction_analysis' AIRFLOW_CTX_TASK_ID='explore_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T17:25:50.549263+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T17:25:50.549263+00:00'
[2024-04-28T17:31:56.817+0000] {logging_mixin.py:154} INFO -                txId
count  2.037690e+05
mean   1.711310e+08
std    1.104655e+08
min    1.076000e+03
25%    8.433452e+07
50%    1.624375e+08
75%    2.454798e+08
max    4.032446e+08
[2024-04-28T17:31:56.832+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/.ipynb_checkpoints/bitcoin-checkpoint.py", line 73, in explore_data
    plt.barh(['Unknown', 'Ilicit', 'Licit'], group_class['txId'].values, color=['orange', 'r', 'g'] )
NameError: name 'plt' is not defined
[2024-04-28T17:31:56.859+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=bitcoin_transaction_analysis, task_id=explore_data, execution_date=20240428T172550, start_date=20240428T173151, end_date=20240428T173156
[2024-04-28T17:31:56.876+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 152 for task explore_data (name 'plt' is not defined; 409)
[2024-04-28T17:31:56.919+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-28T17:31:56.938+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
