[2024-05-22T00:49:00.079+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_bitcoin.train_deep_learning scheduled__2024-05-21T00:00:00+00:00 [queued]>
[2024-05-22T00:49:00.088+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_bitcoin.train_deep_learning scheduled__2024-05-21T00:00:00+00:00 [queued]>
[2024-05-22T00:49:00.088+0000] {taskinstance.py:1361} INFO - Starting attempt 6 of 6
[2024-05-22T00:49:00.107+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): train_deep_learning> on 2024-05-21 00:00:00+00:00
[2024-05-22T00:49:00.132+0000] {standard_task_runner.py:57} INFO - Started process 4544 to run task
[2024-05-22T00:49:00.138+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fraud_bitcoin', 'train_deep_learning', 'scheduled__2024-05-21T00:00:00+00:00', '--job-id', '406', '--raw', '--subdir', 'DAGS_FOLDER/fraud.py', '--cfg-path', '/tmp/tmptf3apxwh']
[2024-05-22T00:49:00.146+0000] {standard_task_runner.py:85} INFO - Job 406: Subtask train_deep_learning
[2024-05-22T00:49:00.250+0000] {task_command.py:416} INFO - Running <TaskInstance: fraud_bitcoin.train_deep_learning scheduled__2024-05-21T00:00:00+00:00 [running]> on host 66abfe055500
[2024-05-22T00:49:00.367+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fraud_bitcoin' AIRFLOW_CTX_TASK_ID='train_deep_learning' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-21T00:00:00+00:00'
[2024-05-22T00:49:14.813+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fraud.py", line 204, in train_deep_learning
    accuracy = accuracy_score(y_test, y_pred)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 220, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 93, in _check_targets
    raise ValueError(
ValueError: Classification metrics can't handle a mix of binary and multilabel-indicator targets
[2024-05-22T00:49:14.901+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fraud_bitcoin, task_id=train_deep_learning, execution_date=20240521T000000, start_date=20240522T004900, end_date=20240522T004914
[2024-05-22T00:49:14.994+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 406 for task train_deep_learning (Classification metrics can't handle a mix of binary and multilabel-indicator targets; 4544)
[2024-05-22T00:49:15.214+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-22T00:49:15.379+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
