[2023-12-22T09:11:33.706+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dd_mssql_snapshot.prepare_query_statement manual__2023-12-22T09:10:56.003840+00:00 [queued]>
[2023-12-22T09:11:33.717+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dd_mssql_snapshot.prepare_query_statement manual__2023-12-22T09:10:56.003840+00:00 [queued]>
[2023-12-22T09:11:33.717+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-22T09:11:33.727+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): prepare_query_statement> on 2023-12-22 09:10:56.003840+00:00
[2023-12-22T09:11:33.732+0000] {standard_task_runner.py:57} INFO - Started process 168 to run task
[2023-12-22T09:11:33.736+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dd_mssql_snapshot', 'prepare_query_statement', 'manual__2023-12-22T09:10:56.003840+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/snapshot-json.py', '--cfg-path', '/tmp/tmpwmqjvzyr']
[2023-12-22T09:11:33.737+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask prepare_query_statement
[2023-12-22T09:11:33.786+0000] {task_command.py:416} INFO - Running <TaskInstance: dd_mssql_snapshot.prepare_query_statement manual__2023-12-22T09:10:56.003840+00:00 [running]> on host 90263e0a625e
[2023-12-22T09:11:33.850+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dd_mssql_snapshot' AIRFLOW_CTX_TASK_ID='prepare_query_statement' AIRFLOW_CTX_EXECUTION_DATE='2023-12-22T09:10:56.003840+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-22T09:10:56.003840+00:00'
[2023-12-22T09:11:33.851+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/snapshot-json.py", line 76, in prepare_query_statement
    athena_previous_hour = generate_date_strings()
NameError: name 'generate_date_strings' is not defined
[2023-12-22T09:11:33.860+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dd_mssql_snapshot, task_id=prepare_query_statement, execution_date=20231222T091056, start_date=20231222T091133, end_date=20231222T091133
[2023-12-22T09:11:33.869+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task prepare_query_statement (name 'generate_date_strings' is not defined; 168)
[2023-12-22T09:11:33.914+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-22T09:11:33.929+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
