[2024-05-19T01:14:51.939+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_transaction_analysis.scrub_data scheduled__2024-05-18T00:00:00+00:00 [queued]>
[2024-05-19T01:14:51.965+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_transaction_analysis.scrub_data scheduled__2024-05-18T00:00:00+00:00 [queued]>
[2024-05-19T01:14:51.966+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-05-19T01:14:52.008+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): scrub_data> on 2024-05-18 00:00:00+00:00
[2024-05-19T01:14:52.034+0000] {standard_task_runner.py:57} INFO - Started process 37544 to run task
[2024-05-19T01:14:52.038+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_transaction_analysis', 'scrub_data', 'scheduled__2024-05-18T00:00:00+00:00', '--job-id', '312', '--raw', '--subdir', 'DAGS_FOLDER/bitcoin.py', '--cfg-path', '/tmp/tmpcqf57zgu']
[2024-05-19T01:14:52.042+0000] {standard_task_runner.py:85} INFO - Job 312: Subtask scrub_data
[2024-05-19T01:14:52.117+0000] {task_command.py:416} INFO - Running <TaskInstance: bitcoin_transaction_analysis.scrub_data scheduled__2024-05-18T00:00:00+00:00 [running]> on host 082df2838a30
[2024-05-19T01:14:52.202+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_transaction_analysis' AIRFLOW_CTX_TASK_ID='scrub_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-18T00:00:00+00:00'
[2024-05-19T04:35:32.618+0000] {logging_mixin.py:154} INFO - Data cleaned and merged.
[2024-05-19T06:15:06.548+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2024-05-19T06:15:06.561+0000] {process_utils.py:131} INFO - Sending 15 to group 37544. PIDs of all processes in the group: [37544]
[2024-05-19T06:15:06.561+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 37544
[2024-05-19T06:15:06.562+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-19T06:15:06.585+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bitcoin.py", line 83, in scrub_data
    df_features.to_csv(os.path.join(DATASET_PATH, 'cleaned_datasets', 'df_features.csv'))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 259, in save
    self._save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 264, in _save
    self._save_body()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 302, in _save_body
    self._save_chunk(start_i, end_i)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 313, in _save_chunk
    libwriters.write_csv_rows(
  File "pandas/_libs/writers.pyx", line 55, in pandas._libs.writers.write_csv_rows
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-05-19T06:15:06.608+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin_transaction_analysis, task_id=scrub_data, execution_date=20240518T000000, start_date=20240519T011451, end_date=20240519T061506
[2024-05-19T06:15:06.624+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 312 for task scrub_data (Task received SIGTERM signal; 37544)
[2024-05-19T06:15:06.666+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=37544, status='terminated', exitcode=1, started='01:14:51') (37544) terminated with exit code 1
