[2024-05-04T02:25:54.485+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dd_mssql_snapshot.generate_date_strings scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-05-04T02:25:54.519+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dd_mssql_snapshot.generate_date_strings scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-05-04T02:25:54.520+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-05-04T02:25:54.569+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): generate_date_strings> on 2024-04-01 00:00:00+00:00
[2024-05-04T02:25:54.600+0000] {standard_task_runner.py:57} INFO - Started process 138 to run task
[2024-05-04T02:25:54.616+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dd_mssql_snapshot', 'generate_date_strings', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/ARCHIVE/.ipynb_checkpoints/test-date-checkpoint.py', '--cfg-path', '/tmp/tmpw5q8da19']
[2024-05-04T02:25:54.620+0000] {standard_task_runner.py:85} INFO - Job 166: Subtask generate_date_strings
[2024-05-04T02:25:54.953+0000] {task_command.py:416} INFO - Running <TaskInstance: dd_mssql_snapshot.generate_date_strings scheduled__2024-04-01T00:00:00+00:00 [running]> on host ea9e10828151
[2024-05-04T02:25:55.217+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dd_mssql_snapshot' AIRFLOW_CTX_TASK_ID='generate_date_strings' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-05-04T02:25:55.234+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ARCHIVE/.ipynb_checkpoints/test-date-checkpoint.py", line 48, in generate_date_strings
    d = datetime.strptime(str(t), "%Y-%m-%d %H:%M:%S.%f")
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-04-01 08:00:00' does not match format '%Y-%m-%d %H:%M:%S.%f'
[2024-05-04T02:25:55.257+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dd_mssql_snapshot, task_id=generate_date_strings, execution_date=20240401T000000, start_date=20240504T022554, end_date=20240504T022555
[2024-05-04T02:25:55.297+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 166 for task generate_date_strings (time data '2024-04-01 08:00:00' does not match format '%Y-%m-%d %H:%M:%S.%f'; 138)
[2024-05-04T02:25:55.337+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-04T02:25:55.395+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
