[2024-05-22T00:28:37.510+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_bitcoin.train_decision_tree scheduled__2024-05-21T00:00:00+00:00 [queued]>
[2024-05-22T00:28:37.532+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_bitcoin.train_decision_tree scheduled__2024-05-21T00:00:00+00:00 [queued]>
[2024-05-22T00:28:37.535+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 4
[2024-05-22T00:28:37.562+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): train_decision_tree> on 2024-05-21 00:00:00+00:00
[2024-05-22T00:28:37.605+0000] {standard_task_runner.py:57} INFO - Started process 4021 to run task
[2024-05-22T00:28:37.638+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fraud_bitcoin', 'train_decision_tree', 'scheduled__2024-05-21T00:00:00+00:00', '--job-id', '386', '--raw', '--subdir', 'DAGS_FOLDER/fraud.py', '--cfg-path', '/tmp/tmpw536s4u9']
[2024-05-22T00:28:37.650+0000] {standard_task_runner.py:85} INFO - Job 386: Subtask train_decision_tree
[2024-05-22T00:28:37.808+0000] {task_command.py:416} INFO - Running <TaskInstance: fraud_bitcoin.train_decision_tree scheduled__2024-05-21T00:00:00+00:00 [running]> on host 66abfe055500
[2024-05-22T00:28:37.951+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fraud_bitcoin' AIRFLOW_CTX_TASK_ID='train_decision_tree' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-21T00:00:00+00:00'
[2024-05-22T00:28:38.067+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fraud.py", line 94, in train_decision_tree
    dt_model.fit(X_significant_train, y_train)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 959, in fit
    super()._fit(
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 242, in _fit
    X, y = self._validate_data(
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/base.py", line 617, in _validate_data
    X = check_array(X, input_name="X", **check_X_params)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 976, in check_array
    raise ValueError(
ValueError: Found array with 0 feature(s) (shape=(944, 0)) while a minimum of 1 is required by DecisionTreeClassifier.
[2024-05-22T00:28:38.086+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fraud_bitcoin, task_id=train_decision_tree, execution_date=20240521T000000, start_date=20240522T002837, end_date=20240522T002838
[2024-05-22T00:28:38.103+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 386 for task train_decision_tree (Found array with 0 feature(s) (shape=(944, 0)) while a minimum of 1 is required by DecisionTreeClassifier.; 4021)
[2024-05-22T00:28:38.178+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-22T00:28:38.217+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
