[2024-05-12T00:01:51.078+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_transaction_analysis.select_features scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-12T00:01:51.084+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_transaction_analysis.select_features scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-12T00:01:51.085+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-05-12T00:01:51.093+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): select_features> on 2024-05-11 00:00:00+00:00
[2024-05-12T00:01:51.103+0000] {standard_task_runner.py:57} INFO - Started process 20597 to run task
[2024-05-12T00:01:51.107+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_transaction_analysis', 'select_features', 'scheduled__2024-05-11T00:00:00+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/bitcoin.py', '--cfg-path', '/tmp/tmphs3pj742']
[2024-05-12T00:01:51.109+0000] {standard_task_runner.py:85} INFO - Job 282: Subtask select_features
[2024-05-12T00:01:51.149+0000] {task_command.py:416} INFO - Running <TaskInstance: bitcoin_transaction_analysis.select_features scheduled__2024-05-11T00:00:00+00:00 [running]> on host 082df2838a30
[2024-05-12T00:01:51.209+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_transaction_analysis' AIRFLOW_CTX_TASK_ID='select_features' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-11T00:00:00+00:00'
[2024-05-12T00:01:57.186+0000] {logging_mixin.py:154} INFO - Datasets split into training and prediction sets.
[2024-05-12T00:01:57.210+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bitcoin.py", line 138, in select_features
    lasso_cv.fit(X, y)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py", line 1551, in fit
    X, y = self._validate_data(
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/base.py", line 617, in _validate_data
    X = check_array(X, input_name="X", **check_X_params)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 967, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 168)) while a minimum of 1 is required by LassoCV.
[2024-05-12T00:01:57.237+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=bitcoin_transaction_analysis, task_id=select_features, execution_date=20240511T000000, start_date=20240512T000151, end_date=20240512T000157
[2024-05-12T00:01:57.258+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 282 for task select_features (Found array with 0 sample(s) (shape=(0, 168)) while a minimum of 1 is required by LassoCV.; 20597)
[2024-05-12T00:01:57.333+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-12T00:01:57.360+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
