[2023-12-26T08:24:23.105+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dd_mssql_snapshot.generate_date_strings manual__2023-12-26T08:10:28.152796+00:00 [queued]>
[2023-12-26T08:24:23.110+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dd_mssql_snapshot.generate_date_strings manual__2023-12-26T08:10:28.152796+00:00 [queued]>
[2023-12-26T08:24:23.110+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-12-26T08:24:23.116+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): generate_date_strings> on 2023-12-26 08:10:28.152796+00:00
[2023-12-26T08:24:23.120+0000] {standard_task_runner.py:57} INFO - Started process 3021 to run task
[2023-12-26T08:24:23.123+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dd_mssql_snapshot', 'generate_date_strings', 'manual__2023-12-26T08:10:28.152796+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/test-date.py', '--cfg-path', '/tmp/tmphx5rxlaw']
[2023-12-26T08:24:23.124+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask generate_date_strings
[2023-12-26T08:24:23.164+0000] {task_command.py:416} INFO - Running <TaskInstance: dd_mssql_snapshot.generate_date_strings manual__2023-12-26T08:10:28.152796+00:00 [running]> on host 5837c4e7e133
[2023-12-26T08:24:23.225+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dd_mssql_snapshot' AIRFLOW_CTX_TASK_ID='generate_date_strings' AIRFLOW_CTX_EXECUTION_DATE='2023-12-26T08:10:28.152796+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-26T08:10:28.152796+00:00'
[2023-12-26T08:24:23.226+0000] {logging_mixin.py:154} INFO - 2023-12-26 08:10:28.152796+00:00
[2023-12-26T08:24:23.231+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test-date.py", line 51, in generate_date_strings
    fmt_dt_obj = datetime.strptime(fmt_time, "%Y-%m-%dT%H:%M:%S.%f")
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2023-12-26T08:00:00+00:00.000' does not match format '%Y-%m-%dT%H:%M:%S.%f'
[2023-12-26T08:24:23.240+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dd_mssql_snapshot, task_id=generate_date_strings, execution_date=20231226T081028, start_date=20231226T082423, end_date=20231226T082423
[2023-12-26T08:24:23.247+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 47 for task generate_date_strings (time data '2023-12-26T08:00:00+00:00.000' does not match format '%Y-%m-%dT%H:%M:%S.%f'; 3021)
[2023-12-26T08:24:23.256+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-26T08:24:23.271+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
