[2024-05-05T10:48:17.517+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_transaction_analysis.scrub_data manual__2024-05-05T10:48:08.751997+00:00 [queued]>
[2024-05-05T10:48:17.522+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_transaction_analysis.scrub_data manual__2024-05-05T10:48:08.751997+00:00 [queued]>
[2024-05-05T10:48:17.522+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-05-05T10:48:17.528+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): scrub_data> on 2024-05-05 10:48:08.751997+00:00
[2024-05-05T10:48:17.535+0000] {standard_task_runner.py:57} INFO - Started process 3393 to run task
[2024-05-05T10:48:17.537+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_transaction_analysis', 'scrub_data', 'manual__2024-05-05T10:48:08.751997+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/bitcoin.py', '--cfg-path', '/tmp/tmpg0z7yato']
[2024-05-05T10:48:17.541+0000] {standard_task_runner.py:85} INFO - Job 229: Subtask scrub_data
[2024-05-05T10:48:17.580+0000] {task_command.py:416} INFO - Running <TaskInstance: bitcoin_transaction_analysis.scrub_data manual__2024-05-05T10:48:08.751997+00:00 [running]> on host c967b8493ef9
[2024-05-05T10:48:17.644+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_transaction_analysis' AIRFLOW_CTX_TASK_ID='scrub_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T10:48:08.751997+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T10:48:08.751997+00:00'
[2024-05-05T10:48:24.603+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bitcoin.py", line 75, in scrub_data
    df_merged = df_features.merge(df_classes, left_on=0, right_on='txId')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 9843, in merge
    return merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 148, in merge
    op = _MergeOperation(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 737, in __init__
    ) = self._get_merge_keys()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1221, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 1778, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 0
[2024-05-05T10:48:24.658+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=bitcoin_transaction_analysis, task_id=scrub_data, execution_date=20240505T104808, start_date=20240505T104817, end_date=20240505T104824
[2024-05-05T10:48:24.680+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 229 for task scrub_data (0; 3393)
[2024-05-05T10:48:24.711+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-05T10:48:24.764+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
