[2023-12-26T08:32:00.812+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dd_mssql_snapshot.generate_date_strings manual__2023-12-26T08:19:56.938872+00:00 [queued]>
[2023-12-26T08:32:00.836+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dd_mssql_snapshot.generate_date_strings manual__2023-12-26T08:19:56.938872+00:00 [queued]>
[2023-12-26T08:32:00.836+0000] {taskinstance.py:1361} INFO - Starting attempt 10 of 11
[2023-12-26T08:32:00.853+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): generate_date_strings> on 2023-12-26 08:19:56.938872+00:00
[2023-12-26T08:32:00.858+0000] {standard_task_runner.py:57} INFO - Started process 3155 to run task
[2023-12-26T08:32:00.862+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dd_mssql_snapshot', 'generate_date_strings', 'manual__2023-12-26T08:19:56.938872+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/test-date.py', '--cfg-path', '/tmp/tmppmfsdw_d']
[2023-12-26T08:32:00.868+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask generate_date_strings
[2023-12-26T08:32:00.906+0000] {task_command.py:416} INFO - Running <TaskInstance: dd_mssql_snapshot.generate_date_strings manual__2023-12-26T08:19:56.938872+00:00 [running]> on host 5837c4e7e133
[2023-12-26T08:32:00.963+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dd_mssql_snapshot' AIRFLOW_CTX_TASK_ID='generate_date_strings' AIRFLOW_CTX_EXECUTION_DATE='2023-12-26T08:19:56.938872+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-26T08:19:56.938872+00:00'
[2023-12-26T08:32:00.969+0000] {logging_mixin.py:154} INFO - helooww : 2023-12-26 16:19:56.938872
[2023-12-26T08:32:00.970+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test-date.py", line 50, in generate_date_strings
    exec_time = d.replace(second=0, microsecond=0, minute=0)
TypeError: replace() takes no keyword arguments
[2023-12-26T08:32:00.977+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dd_mssql_snapshot, task_id=generate_date_strings, execution_date=20231226T081956, start_date=20231226T083200, end_date=20231226T083200
[2023-12-26T08:32:00.984+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 54 for task generate_date_strings (replace() takes no keyword arguments; 3155)
[2023-12-26T08:32:00.994+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-26T08:32:01.012+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
