[2023-12-26T08:23:40.003+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dd_mssql_snapshot.generate_date_strings manual__2023-12-26T08:19:56.938872+00:00 [queued]>
[2023-12-26T08:23:40.009+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dd_mssql_snapshot.generate_date_strings manual__2023-12-26T08:19:56.938872+00:00 [queued]>
[2023-12-26T08:23:40.009+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 4
[2023-12-26T08:23:40.017+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): generate_date_strings> on 2023-12-26 08:19:56.938872+00:00
[2023-12-26T08:23:40.022+0000] {standard_task_runner.py:57} INFO - Started process 3009 to run task
[2023-12-26T08:23:40.026+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dd_mssql_snapshot', 'generate_date_strings', 'manual__2023-12-26T08:19:56.938872+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/test-date.py', '--cfg-path', '/tmp/tmpq6gq5j18']
[2023-12-26T08:23:40.027+0000] {standard_task_runner.py:85} INFO - Job 45: Subtask generate_date_strings
[2023-12-26T08:23:40.066+0000] {task_command.py:416} INFO - Running <TaskInstance: dd_mssql_snapshot.generate_date_strings manual__2023-12-26T08:19:56.938872+00:00 [running]> on host 5837c4e7e133
[2023-12-26T08:23:40.133+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dd_mssql_snapshot' AIRFLOW_CTX_TASK_ID='generate_date_strings' AIRFLOW_CTX_EXECUTION_DATE='2023-12-26T08:19:56.938872+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-26T08:19:56.938872+00:00'
[2023-12-26T08:23:40.134+0000] {logging_mixin.py:154} INFO - 2023-12-26 08:19:56.938872+00:00
[2023-12-26T08:23:40.139+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test-date.py", line 51, in generate_date_strings
    fmt_dt_obj = datetime.strptime(fmt_time, "%Y-%m-%dT%H:%M:%S.%f")
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2023-12-26T08:00:00+00:00.000' does not match format '%Y-%m-%dT%H:%M:%S.%f'
[2023-12-26T08:23:40.147+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dd_mssql_snapshot, task_id=generate_date_strings, execution_date=20231226T081956, start_date=20231226T082340, end_date=20231226T082340
[2023-12-26T08:23:40.154+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 45 for task generate_date_strings (time data '2023-12-26T08:00:00+00:00.000' does not match format '%Y-%m-%dT%H:%M:%S.%f'; 3009)
[2023-12-26T08:23:40.160+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-26T08:23:40.174+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
