[2023-12-26T08:19:57.521+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dd_mssql_snapshot.generate_date_strings manual__2023-12-26T08:19:56.938872+00:00 [queued]>
[2023-12-26T08:19:57.527+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dd_mssql_snapshot.generate_date_strings manual__2023-12-26T08:19:56.938872+00:00 [queued]>
[2023-12-26T08:19:57.528+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-26T08:19:57.536+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): generate_date_strings> on 2023-12-26 08:19:56.938872+00:00
[2023-12-26T08:19:57.540+0000] {standard_task_runner.py:57} INFO - Started process 2949 to run task
[2023-12-26T08:19:57.542+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dd_mssql_snapshot', 'generate_date_strings', 'manual__2023-12-26T08:19:56.938872+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/test-date.py', '--cfg-path', '/tmp/tmpn0ajb4ih']
[2023-12-26T08:19:57.543+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask generate_date_strings
[2023-12-26T08:19:57.665+0000] {task_command.py:416} INFO - Running <TaskInstance: dd_mssql_snapshot.generate_date_strings manual__2023-12-26T08:19:56.938872+00:00 [running]> on host 5837c4e7e133
[2023-12-26T08:19:57.811+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dd_mssql_snapshot' AIRFLOW_CTX_TASK_ID='generate_date_strings' AIRFLOW_CTX_EXECUTION_DATE='2023-12-26T08:19:56.938872+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-26T08:19:56.938872+00:00'
[2023-12-26T08:19:57.815+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test-date.py", line 49, in generate_date_strings
    prev_hr = (fmt_time - timedelta(hours=1)).isoformat() + ".000"
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
[2023-12-26T08:19:57.825+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dd_mssql_snapshot, task_id=generate_date_strings, execution_date=20231226T081956, start_date=20231226T081957, end_date=20231226T081957
[2023-12-26T08:19:57.834+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task generate_date_strings (unsupported operand type(s) for -: 'str' and 'datetime.timedelta'; 2949)
[2023-12-26T08:19:57.879+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-26T08:19:57.895+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
